// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/vendor-flow/Menu.tsx": () => import("../components/mockups/vendor-flow/Menu.tsx"),
  "./components/mockups/vendor-flow/Orders.tsx": () => import("../components/mockups/vendor-flow/Orders.tsx"),
  "./components/mockups/vendor-flow/Store.tsx": () => import("../components/mockups/vendor-flow/Store.tsx"),
  "./components/mockups/vendor-flow/VendorDashboard.tsx": () => import("../components/mockups/vendor-flow/VendorDashboard.tsx"),
  "./components/mockups/vendor-flow/Verification.tsx": () => import("../components/mockups/vendor-flow/Verification.tsx")
};
